services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: matchdb
      POSTGRES_USER: panos
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - matchnet

  app:
    build:
      context: .
    container_name: match-odds-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/matchdb
      SPRING_DATASOURCE_USERNAME: panos
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - matchnet

volumes:
  pgdata:

networks:
  matchnet: {}
